adding actual file for bin/rootsrc

diff --git a/bin/rootsrc b/bin/rootsrc
--- a/bin/rootsrc
+++ b/bin/rootsrc
@@ -1,1 +1,98 @@
-/home/mark/rat-pac/user/shell_scripts/rootsrc
+#!/bin/bash
+# rootsrc -- simple script to view the source files for a given ROOT class
+# USAGE: rootsrc [-h|-p] <ROOTClassName>
+# ~ Mark J. Duvall ~ duvall3@github.com ~ 7/2021 ~ #
+#
+
+##Copyright (C) 2021 Mark J. Duvall
+##
+##    This program is free software: you can redistribute it and/or modify
+##    it under the terms of the GNU General Public License as published by
+##    the Free Software Foundation, either version 3 of the License, or
+##    (at your option) any later version.
+##
+##    This program is distributed in the hope that it will be useful,
+##    but WITHOUT ANY WARRANTY; without even the implied warranty of
+##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+##    GNU General Public License for more details.
+##
+##    You should have received a copy of the GNU General Public License
+##    along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
+# help
+usage() {
+  echo -e "USAGE: rootsrc [-h|-p] <ROOTClassName>"
+  echo -e "  -h\t\tShow this help message and exit"
+  echo -e "  -p\t\tprint filenames and exit"
+}
+
+# arg check
+if [[ ! $1 ]]; then
+  usage
+  exit 10
+fi
+
+# option(s)
+PRINT_ONLY=false
+while getopts ":hp" OPTIONS; do
+  case $OPTIONS in
+    h)
+      usage
+      exit 5
+      ;;
+    p)
+      PRINT_ONLY=true
+      ;;
+    *)
+      usage
+      exit 10
+      ;;
+  esac
+done
+shift $((OPTIND-1))
+
+# init
+ERR=/dev/stderr
+HFILE_NAME="$1".h
+CFILE_NAME="$1".cxx
+
+# locate files
+HFILE=$(find $ROOTSYS -name $HFILE_NAME | head -n 1)
+CFILE=$(find $ROOTSYS -name $CFILE_NAME | head -n 1)
+if [[ $HFILE ]]; then
+  HFILE_TF=true
+else
+  HFILE_TF=false
+  echo "Warning: Header file $HFILE_NAME not found." > $ERR
+fi
+if [[ $CFILE ]]; then
+  CFILE_TF=true
+else
+  CFILE_TF=false
+  echo "Warning: Source file $CFILE_NAME not found." > $ERR
+fi
+if (! $HFILE_TF) && (! $CFILE_TF); then
+  echo "Error: No .h or .cxx files for class \"$1\" found under $ROOTSYS. Searching for mentions..." > $ERR
+  GREPLIST=$(grep -iE -IRl $1 "$ROOTSYS" 2> /dev/null)
+  if [[ $GREPLIST ]]; then
+    echo -e "\nMentions of \"$1\" found in the following files:\n"
+    echo $GREPLIST | sed s@$ROOTSYS@'$ROOTSYS'@g | tr ' ' '\n'
+    echo
+    exit 2
+  else
+    echo -e "No mentions of \"$1\" found under $ROOTSYS/src. Exiting.\n"
+    exit 3
+  fi
+fi
+
+# main
+echo -e "$HFILE\n$CFILE"
+if $PRINT_ONLY; then
+  exit 0
+else
+  # open for reading only
+  vim -R -c ":set filetype+=.root" -c ":au BufNewFile,BufRead * set filetype+=.root" -p $HFILE $CFILE
+fi
+
+# all pau!   )
+exit 0
